name: supermarket
description: super market app


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.2
  dio: ^4.0.6
  buildcondition: ^0.0.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  http: ^0.13.5
  fluttertoast: ^8.0.9
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15
  dartz: ^0.10.1
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  flutter_spinkit: ^5.1.0
  path_provider: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1



flutter:

  uses-material-design: true
  assets:
    - assets/images/loading_image.jpg

  fonts:
    - family: lato
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
